// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// Copyright (c) 2025, Andres Felipe Corrales Ortiz.
// All rights reserved.
//
// Generated by jnigen. Do not edit!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.hapkiduki.infrared_plugin.IrController`
class IrController extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<IrController> $type;

  @jni$_.internal
  IrController.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/hapkiduki/infrared_plugin/IrController',
  );

  /// The type which includes information such as the signature of this class.
  static const nullableType = $IrController$NullableType();
  static const type = $IrController$Type();
  static final _id_INSTANCE = _class.staticFieldId(
    r'INSTANCE',
    r'Lcom/hapkiduki/infrared_plugin/IrController;',
  );

  /// from: `static public final com.hapkiduki.infrared_plugin.IrController INSTANCE`
  /// The returned object must be released after use, by calling the [release] method.
  static IrController get INSTANCE =>
      _id_INSTANCE.get(_class, const $IrController$Type());

  static final _id_initialize = _class.instanceMethodId(
    r'initialize',
    r'(Landroid/content/Context;)V',
  );

  static final _initialize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void initialize(android.content.Context context)`
  void initialize(jni$_.JObject context) {
    final _$context = context.reference;
    _initialize(
      reference.pointer,
      _id_initialize as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).check();
  }

  static final _id_hasIrEmitter = _class.staticMethodId(
    r'hasIrEmitter',
    r'()Z',
  );

  static final _hasIrEmitter =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final boolean hasIrEmitter()`
  static bool hasIrEmitter() {
    return _hasIrEmitter(
      _class.reference.pointer,
      _id_hasIrEmitter as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_getCarrierFrequencies = _class.staticMethodId(
    r'getCarrierFrequencies',
    r'()[I',
  );

  static final _getCarrierFrequencies =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public final int[] getCarrierFrequencies()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JIntArray? getCarrierFrequencies() {
    return _getCarrierFrequencies(
      _class.reference.pointer,
      _id_getCarrierFrequencies as jni$_.JMethodIDPtr,
    ).object<jni$_.JIntArray?>(const jni$_.JIntArrayNullableType());
  }

  static final _id_transmitHex = _class.staticMethodId(
    r'transmitHex',
    r'(ILjava/lang/String;)V',
  );

  static final _transmitHex =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public final void transmitHex(int i, java.lang.String string)`
  static void transmitHex(int i, jni$_.JString string) {
    final _$string = string.reference;
    _transmitHex(
      _class.reference.pointer,
      _id_transmitHex as jni$_.JMethodIDPtr,
      i,
      _$string.pointer,
    ).check();
  }

  static final _id_transmitInts = _class.staticMethodId(
    r'transmitInts',
    r'(I[I)V',
  );

  static final _transmitInts =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public final void transmitInts(int i, int[] is)`
  static void transmitInts(int i, jni$_.JIntArray is$) {
    final _$is$ = is$.reference;
    _transmitInts(
      _class.reference.pointer,
      _id_transmitInts as jni$_.JMethodIDPtr,
      i,
      _$is$.pointer,
    ).check();
  }
}

final class $IrController$NullableType extends jni$_.JObjType<IrController?> {
  @jni$_.internal
  const $IrController$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/hapkiduki/infrared_plugin/IrController;';

  @jni$_.internal
  @core$_.override
  IrController? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : IrController.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<IrController?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($IrController$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($IrController$NullableType) &&
        other is $IrController$NullableType;
  }
}

final class $IrController$Type extends jni$_.JObjType<IrController> {
  @jni$_.internal
  const $IrController$Type();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/hapkiduki/infrared_plugin/IrController;';

  @jni$_.internal
  @core$_.override
  IrController fromReference(jni$_.JReference reference) =>
      IrController.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<IrController?> get nullableType =>
      const $IrController$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($IrController$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($IrController$Type) &&
        other is $IrController$Type;
  }
}
