import 'dart:typed_data';

import 'package:infrared_plugin/bindings.dart';
import 'package:jni/jni.dart';

/// {@template infrared_plugin}
/// A Flutter plugin that provides an interface to interact with a device's
/// infrared (IR) emitter.
///
/// This class utilizes JNI bindings, generated by `jnigen`, to communicate
/// with the native Android (Kotlin/Java) `IrController` implementation.
/// {@endtemplate}
final class InfraredPlugin {
  /// The singleton instance of [InfraredPlugin].
  ///
  /// Access the plugin's functionality through this instance:
  /// ```dart
  /// final plugin = InfraredPlugin();
  /// ```
  static final InfraredPlugin _instance = InfraredPlugin._internal();

  // Internal reference to the Android Context.
  // This is initialized once per application lifecycle for the singleton.
  final JObject _activity;

  /// Private constructor for the [InfraredPlugin] singleton.
  ///
  /// This initializes the native `IrController` instance using the current
  /// Android activity context.
  InfraredPlugin._internal()
    : _activity = JObject.fromReference(Jni.getCurrentActivity()) {
    IrController.INSTANCE.initialize(_activity);
  }

  /// {@macro infrared_plugin_instance}
  ///
  /// Provides the singleton instance of [InfraredPlugin].
  ///
  /// It's a factory constructor, ensuring only one instance of the plugin
  /// exists throughout the application.
  factory InfraredPlugin() {
    return _instance;
  }

  /// Checks if the device possesses an infrared (IR) emitter.
  ///
  /// This is crucial before attempting any IR transmission.
  ///
  /// Returns `true` if an IR emitter is present, `false` otherwise.
  Future<bool> hasIrEmitter() async {
    return IrController.hasIrEmitter();
  }

  /// Retrieves the carrier frequency ranges supported by the device's IR emitter.
  ///
  /// This method is typically called to determine the valid frequencies
  /// for `transmitHex` or `transmitInts`.
  ///
  /// Returns a `List<List<int>>`, where each inner list represents a
  /// `[minFrequency, maxFrequency]` pair in Hertz (Hz).
  /// Returns an empty list `[]` if no frequencies are supported or
  /// if the underlying native call returns null.
  Future<List<List<int>>> getCarrierFrequencies() async {
    final freqs = IrController.getCarrierFrequencies();
    if (freqs == null) {
      return [];
    }
    final result = <List<int>>[];
    // The native array is flat [min1, max1, min2, max2], convert it to a list of pairs.
    for (var i = 0; i < freqs.length; i += 2) {
      if (i + 1 < freqs.length) {
        result.add([freqs[i], freqs[i + 1]]);
      }
    }
    // Release the native array to prevent memory leaks.
    freqs.release();
    return result;
  }

  /// Transmits an infrared (IR) pattern using a space-separated hexadecimal string.
  ///
  /// This method is suitable for sending raw IR commands where the pattern
  /// is defined as a sequence of hexadecimal pulse durations.
  ///
  /// - `frequency`: The carrier frequency in Hertz (Hz) for the IR signal.
  ///   This frequency should ideally fall within the ranges returned by
  ///   [getCarrierFrequencies].
  /// - `hexPattern`: A `String` containing space-separated hexadecimal values.
  ///   Each value represents a pulse duration (on/off) in microseconds.
  ///   Example: `"00C8 00C8 01F4 00C8"`
  Future<void> transmitHex({
    required int frequency,
    required String hexPattern,
  }) async {
    // Convert the Dart String to a JNI JString to pass it to Kotlin.
    final jPattern = hexPattern.toJString();
    IrController.transmitHex(frequency, jPattern);
    jPattern.release();
  }

  /// Transmits an infrared (IR) pattern using a list of integer pulse durations.
  ///
  /// This method provides a direct way to send IR commands where the pattern
  /// is defined as a sequence of integer pulse durations.
  ///
  /// - `frequency`: The carrier frequency in Hertz (Hz) for the IR signal.
  ///   This frequency should ideally fall within the ranges returned by
  ///   [getCarrierFrequencies].
  /// - `pattern`: A `List<int>` where each integer represents a pulse duration
  ///   (on/off) in microseconds.
  ///   Example: `[200, 200, 500, 200]`
  Future<void> transmitInts({
    required int frequency,
    required List<int> pattern,
  }) async {
    // Convert the Dart List<int> to a JNI JIntArray.
    final jPattern = Int32List.fromList(pattern);
    final JIntArray jIntArrayPattern = JIntArray(jPattern.length);
    jIntArrayPattern.setRange(0, jPattern.length, jPattern);
    IrController.transmitInts(frequency, jIntArrayPattern);
    jIntArrayPattern.release();
  }
}
